### ISSUE TITLE
Can not compare objects that have been parsed

### ISSUE THREAD

**Issue by gavk34** [multi-io/xml-mapping#6]
Using Ruby .eql? on the objects created using the load_from_xml(xml) they are not identical. Looks to be due to the fact that the nodes are separate class ids. Is there a way to compare the objects?

**Comment by multi-io** [comment]
Well, xml-mapping is about XML mapping, so it doesn't concern itself with object equality. So I guess if you want equality semantics that differ from what's inherited from Object (or whatever base class you're inheriting from), you'd have to implement your own .eql? / == as needed.
